version: '2.3'
services:
  database:
    image: quay.io/azavea/postgis:2.3-postgres9.6-slim
    environment:
      - POSTGRES_USER=$name;format="norm"$
      - POSTGRES_PASSWORD=$name;format="norm"$
      - POSTGRES_DB=$name;format="norm"$
    ports:
      - "$default_db_port$:$default_db_port$"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$name;format="norm"$"]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 5s
