#!/bin/bash
set -eu

function usage() {
    echo -n \
"Usage: \$(basename "\$0")
Use Docker Compose to enter a psql shell on the local database container
"
}

if [ "\${BASH_SOURCE[0]}" = "\${0}" ]
then
    case "\${1:-}" in
        --help)
            usage
            ;;
        *)
            echo -e "\e[32m[$name$] Starting dbshell...\e[0m"
            docker-compose run --rm -e PGPASSWORD=$name;format="norm"$ database psql -U $name;format="norm"$ -h database
            ;;
    esac
fi
