#!/bin/bash

set -e

if [[ -n "\${$name;format="upper,snake"$_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: \$(basename "\$0") [flyway command]

Runs app-backend migrations via flywaydb CLI

Available flyway commands are migrate|clean|info|validate|undo|baseline|repair

"
}

if [ "\${BASH_SOURCE[0]}" = "\${0}" ]
then
    case "\${1}" in
        --help)
            usage
            ;;
        *)
            echo -e "\e[32m[$name$] Running migrations\e[0m"
            sbt 'application/run migrate'
            ;;
    esac
fi
