#!/bin/bash

set -e


if [[ -n "\${$name;format="upper,snake"$_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: \$(basename "\$0")

Starts servers using docker-compose.
"
}


if [ "\${BASH_SOURCE[0]}" = "\${0}" ]
then
    case "\${1}" in
        --help)
            usage
            ;;
        *)
            echo -e "\e[32m[$name$] Starting API service\e[0m"
            sbt 'application/run serve'
            ;;
    esac
fi
