#!/bin/bash

set -e

if [[ -n "\${$name;format="upper,snake"$_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: \$(basename "\$0")
Attempts to setup the project's development environment.
"
}


if [ "\${BASH_SOURCE[0]}" = "\${0}" ]
then

    case "\${1}" in
        --help)
            usage
            ;;
        *)
            echo -e "\e[32m[$name$] Running Setup...\e[0m"
            ./scripts/update
    esac
fi
