#!/bin/bash

set -e


if [[ -n "\${$name;format="upper,snake"$_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: \$(basename "\$0")
Setup external project dependencies.
"
}


if [ "\${BASH_SOURCE[0]}" = "\${0}" ]
then
    case "\${1}" in
        --help)
            usage
            ;;
        *)
            echo -e "\e[32m[$name$] Compiling and formatting application...\e[0m"
            sbt ";application/compile; scalafmt; scalafmtSbt"
            docker-compose up -d database
            ./scripts/migrate
    esac
fi
