name: Automerge Dependencies

on:
  workflow_run:
    types:
      - completed
    workflows:
      - CI

jobs:
  merge-dependabot:
    runs-on: ubuntu-latest
    steps:
      - uses: ridedott/merge-me-action@v2.10.31
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        with:
          GITHUB_LOGIN: dependabot
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  merge-scala-steward:
    runs-on: ubuntu-latest
    steps:
      - uses: ridedott/merge-me-action@v2.10.31
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        with:
          GITHUB_LOGIN: azavea-bot
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
